### ISSUE TITLE
How to insert named arguments in function snippet

### ISSUE THREAD

**Issue by sellithy** [fannheyward/coc-pyright#1115]
Apologies if this is not the correct channel to ask this

If I have
```
def foo(param1: float, param2: float): ...
```
I want to type foo<TAB> and get
```
foo(
    param1=$1,
    param2=$2,
)$0
```
1. Does coc-pyright support this right now?
    a. I think I've done enough research to say no because Pyright itself doesn't but want to double check
    b. I know, however, that coc-pyright add `()` after function names which Pyright itself doesn't add ([code link](https://github.com/fannheyward/coc-pyright/blob/master/src/middleware.ts#L121))
2. If not, would this be a good addition to coc-pyright (not Pyright)?
3. If yes, how hard would it be to implement and can I get some pointers on how to implement it?

**Comment by fannheyward** [comment]
coc-pyright doesn't support this, and there's no way to implement this because Pyright didn't return parameters info, let's use `foo` for example, here's what Pyright returns:

```
{
  label: 'foo',
  kind: 3,
  data: {
    uri: 'file:///Users/fannheyward/src/hello-p/meta.py',
    position: { line: 19, character: 3 },
    symbolLabel: 'foo'
  },
  sortText: '09.9999.foo'
}
```

Only label `foo`, no parameters/arguments.

Then coc.nvim requests to resolve the completion item:

```
{
    "label": "foo",
    "kind": 3,
    "data": {
        "uri": "file:///Users/fannheyward/src/hello-p/meta.py",
        "position": {
            "line": 20,
            "character": 3
        },
        "symbolLabel": "foo"
    },
    "sortText": "09.9999.foo",
    "insertText": "foo($1)$0",
    "insertTextFormat": 2,
    "documentation": {
        "kind": "markdown",
        "value": "```python\ndef foo(\n    param1: float,\n    param2: float\n) -> None\n```"
    }
}
```

The markdown document is what you got in the floating window. Can we use the document to implement this? yes or no, we need to resolve all items, parses the document, add parameters to insertText like https://github.com/fannheyward/coc-pyright/blob/master/src/middleware.ts#L121, this is too expensive because Pyright returns 120+ items after inputing `f`.
