### ISSUE TITLE
problem with setting the interpreter

### ISSUE THREAD

**Issue by amirongit** [fannheyward/coc-pyright#131]
python.setInterpreter doesn't work for me, heres the problem:
if I have python.pythonPath in my coc config, I can't change the intrepreter when I want to use a virtual environment,
to solve this, I removed python.pythonPath from coc config and now I can use my venv interpreter, but now I can't use pyright outside of my project, cause I removed python.pythonPath from coc config and now pyright has no interpreters to work with,

so I put it back in the coc config file, now it works fine out of projects, but in the projects? it doesn't know my imports ( cause they are installed in a venv ) and python.setInterpreter doesn't work AT ALL.

I'll try to record my screen to show it...

**Comment by fannheyward** [comment]
There's no `python.setInterpreter ` in coc-pyright, checkout https://github.com/fannheyward/coc-pyright/issues/99

**Comment by amirongit** [comment]
> There's no `python.setInterpreter ` in coc-pyright, checkout #99

so how can I switch to my venv python interpreters ? I have set python.venvPath in coc config

**Comment by fannheyward** [comment]
I prefer to set `python.pythonPath` to `python`, and switch the venv out vim, https://github.com/fannheyward/coc-pyright/issues/67#issuecomment-670292342

**Comment by fannheyward** [comment]
I prefer to set `python.pythonPath` to `python`, and switch the venv out vim, https://github.com/fannheyward/coc-pyright/issues/67#issuecomment-670292342

**Comment by CharlieCheckpt** [comment]
Hi @fannheyward ! First, thank you for this really nice package. 

I've had some trouble recently for coc-pyright to use the correct python interpreter, an issue similar to the one of the author.
I have a python interpreter specific to my project, which was created using `virtualenv`.

I do the same steps than you recommended [here](https://github.com/fannheyward/coc-pyright/issues/67#issuecomment-670292342), that is first source my environment and then launch vim. 
But as you can see below, it uses the default python of the system, instead of using the one of my virtual environment.

I also tried specifying the setting `python.pythonPath` in `~/.config/nvim/coc-settings.json`, to no avail. 

**What's the output of `:CocCommand pyright.version`**
```
coc-pyright 1.1.194 with Pyright 1.1.202
```

**What's the output of `:CocCommand workspace.showOutput Pyright`**
```
Workspace: /HOMES/chs/workspace/my_project
Using python from /fusionio/opt/anaconda3/bin/python

[Info  - 8:35:48 AM] Pyright language server 1.1.202 starting  
[Info  - 8:35:48 AM] Server root directory: /fusionio/home/chs/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist
[Info  - 8:35:48 AM] No configuration file found. 
[Info  - 8:35:48 AM] No pyproject.toml file found.
[Info  - 8:35:48 AM] Setting pythonPath for service "my_project": "/fusionio/opt/anaconda3/bin/python"
[Warn  - 8:35:48 AM] stubPath /HOMES/chs/workspace/msi_pred/typings is not a valid directory. 
[Info  - 8:35:48 AM] Assuming Python version 3.6 
[Info  - 8:35:48 AM] Assuming Python platform Linux
```

Any help would be greatly appreciated.
