### ISSUE TITLE
coc-pyright vs. coc-jedi

### ISSUE THREAD

**Issue by BonaBeavis** [fannheyward/coc-pyright#431]
How do coc-pyright and coc-jedi differ? I had both because I thought pyright is just a static code checker, but it also provides jump functions like jumpDefinition.

**Comment by fannheyward** [comment]
1. coc-pyright is based on Pyright, static type checker for Python, which also provides LSP features such as complet suggestions, hover documents, goto definitions and so on.
2. coc-jedi is a wrapper of [jedi-language-server](https://github.com/pappasam/jedi-language-server), based on Jedi
3. So the main different is Pyright or Jedi
4. Pyright is came from Microsoft and in very active and quickly development, with a very fast analyze speed. Because it's coded in Typescript and runs on Nodejs, it's may difficult to use Python tools from community.
5. Jedi has an advantages in Python community tools sharing
5. The Pylance is based on Pyright, works with vscode-python that has more Python tools, the latest vscode-python also adds jedi-language-server support
6. coc-pyright also ports some features from vscode-python, runs Python tools like black, pylint etc

You can use both coc-pyright and coc-jedi with your project.

**Comment by sisrfeng** [comment]
> it's may difficult

应该是It may be difficult 吧
