### ISSUE TITLE
Enable GitHub Sponsors

### ISSUE THREAD

**Issue by panosl** [fannheyward/coc-pyright#433]
I'd like the option to donate monthly through GitHub sponsors, rather than patreon etc. I've set a donation for neovim, and it's easier to handle it all from here.

With $2, $5, $10 tiers. I think it'll help with more people contributing.

**Comment by fannheyward** [comment]
I'm very glad and happy to hear that you like coc-pyright and my works can help you, thank you.

But I can't setup GitHub Sponsors because it's not available in China by now 😞, that's why I setup Patreon. You can also do a one-time PayPal https://www.paypal.com/paypalme/fannheyward (it's never a force)

Thank you for your like.

**Comment by fannheyward** [comment]
Hi @panosl, I've received the PayPal me and updated the Patreon tier, thank you again.
