### ISSUE TITLE
Incorrect [Pyright reportMissingImports] in simple filestructure

### ISSUE THREAD

**Issue by awkh88** [fannheyward/coc-pyright#459]
**What's the output of `:CocCommand pyright.version`**

macOS Big Sur 11.3, NeoVim v0.4.4, coc.nvim v0.0.80 and coc-pyright 1.1.136

I have the following file structure:

- directory
       - scripty.py
       - util.py

script.py imports a function from util.py using 'from util import <function name>

Pyright reports that this import cannot be resolved.
<img width="901" alt="Screenshot 2021-05-02 at 11 38 48" src="https://user-images.githubusercontent.com/17640915/116808779-fada5e80-ab3a-11eb-8f32-2b5926e0d4be.png">
Pyright is linked to the version of python in my conda evn, and the code executes without errors. 

I have attached the code so that you can try to replicate the error warning.
[task5.5.zip](https://github.com/fannheyward/coc-pyright/files/6411511/task5.5.zip)

What is causing this error warning? How do I fix it? :)

Thank you!

**Comment by mortenoj** [comment]
I just had a similar problem. Seemed to be because coc-vim considered another folder the workspace root because I was working in a sub-folder in a git repository. ref: https://github.com/fannheyward/coc-pyright/issues/64#issuecomment-739539359

a workaround could be to create a specific file in your project folder such as `.python-root` and add it as the first element in `coc.preferences.rootPatterns` in coc-settings.json

```json
  "coc.preferences.rootPatterns": [
    ".python-root",
    ".git",
    ".hg",
    ".projections.json"
  ],
```
this solved my issue

**Comment by fannheyward** [comment]
```
❯ fd
dataIO
dataIO/dataset_240300_10.txt
dataIO/testInput.txt
script.py
util.py
```

I init project above, everything works as expected. As @mortenoj said, it's a workspace root issue.
