### ISSUE TITLE
Trigger auto-import feature in vim normal mode

### ISSUE THREAD

**Issue by emarbo** [fannheyward/coc-pyright#752]
Hello there! 

I use the Auto-import feature very often when typing but I would love to trigger the same in vim normal mode.

Let's suppose I have copy-pasted a chunk of code and there are some "xxxx is not defined" that I have to import, that's what I do:
1. Go to the end of the word
2. Enter insert mode
3. Trigger autocompletion
4. Select the Auto-import option
5. Go again to normal mode
6. Jump to the next issue

I feel like triggering the Auto-import feature in normal mode would be very timesaving. I didn't find this option on readme or CocCommand or CocAction, am I missing something? If this doesn't exist, is it feasible?

Notice that there might be more than one Auto-import option and the user should be able to choose what to use as they are currently doing at point 4.

Thanks!

**Comment by fannheyward** [comment]
<img width="360" alt="截屏2022-05-19 15 42 08" src="https://user-images.githubusercontent.com/345274/169239803-95a6d48a-3411-432b-9623-b7eb79766b06.png">

Put your cursor on the `not defined` word, trigger `<Plug>(coc-codeaction-cursor)`.

**Comment by emarbo** [comment]
Hi @fannheyward, thanks for your blazing fast reply. I didn't know that this feature existed!

I tried it but it seems this feature is different than the one triggered by:

![2022-05-19T10:44:03,769367774+02:00](https://user-images.githubusercontent.com/2648102/169252276-4be723a3-3aba-4eb8-8d0e-14960685347c.png)

Because when I use the one you suggested I got the following error:

```
[coc.nvim] Module rope not installed
```

Any ideas why this is happening?

**Comment by fannheyward** [comment]
Yes, they're different.

The auto-import in insert mode is provided by Pyright with more power and intelligent, but we can't use this from CodeAction because Pyright didn't open this https://github.com/microsoft/pyright/issues/251.

The CodeAction from normal mode is provided by coc-pyright, a very simple auto-import implementation:

1. check the `not defined` diagnostic to get the missing module name
2. provide `import x` or `from _ import x` code actions
3. run `rope.refactor.importutils` to add the `import x` to the file. This is why the `rope` is needed

Back to your question, the auto-import code action in normal mode is very feature-limited, maybe incorrect, just a helper.

**Comment by emarbo** [comment]
Hi @fannheyward, it's a pity that pyright doesn't give support for this feature but there's nothing to do with that. Thanks for your time and deeply complete explanation.
